### ISSUE TITLE
Can you please provide a sample data set so that code can be run without downloading ?

### ISSUE THREAD

**Issue by shaktisd** [dongjun-Lee/text-summarization-tensorflow#1]
I have limited compute power on my laptop, it will be really useful t study the code locally if you can provide a small dataset using which I can run it locally on my laptop and debug the code.
Thanks
Shakti

**Comment by dongjun-Lee** [comment]
Hi, Shakti. I uploaded [sample_data.zip](sample_data.zip) with 10000 training samples and 1000 validation samples. Thanks.
