### ISSUE TITLE
Using previous trained models

### ISSUE THREAD

**Issue by PauloQuerido** [dongjun-Lee/text-summarization-tensorflow#11]
Hi.

You actual code always trains from the beginning. But Tensorflow permits training after a certain model, or checkpoint, and this is really useful.

I added a few lines to my train.py. This does not deserve a Pull Request, I believe. So I just let the lines here for later use / adaptation /inspiration / ignoring.

Add an argument:
`    parser.add_argument("--reuse", action="store_true", help="Reuse previously trained model")
`

Check checkpoint and argument:
after 
`if not os.path.exists("saved_model"):`
`     os.mkdir("saved_model")`

add 
`else:`
    `if args.reuse:`
        `old_model_checkpoint_path = open('saved_model/checkpoint', 'r')`
        `old_model_checkpoint_path = "".join(["saved_model/",old_model_checkpoint_path.read().splitlines()[0].split('"')[1] ])`

Restore model to session:
near `saver = tf.train.Saver(tf.global_variables())`
add
`if 'old_model_checkpoint_path' in globals():`
`        print("Continuing from previous trained model " , old_model_checkpoint_path , "...")`
`        saver.restore(sess,  old_model_checkpoint_path ) `

**Comment by dongjun-Lee** [comment]
@PauloQuerido Hi. I think this functionality will be very helpful! Could you make a pull request for this? I'll be very appreciated 👍.

**Comment by PauloQuerido** [comment]
Sure. Will do later today or in the weekend.
