### ISSUE TITLE
How to increase the article size ?

### ISSUE THREAD

**Issue by suryacaprice** [dongjun-Lee/text-summarization-tensorflow#16]
As of now its only reading small articles , how to increase the article size to a large one ?

**Comment by vtrokhymenko** [comment]
in this line u can edit chars article https://github.com/dongjun-Lee/text-summarization-tensorflow/blob/9659a7bd78cb8eab899ef5a5dc9c87462884a277/utils.py#L58

**Comment by dongjun-Lee** [comment]
@vtrokhymenko Thank you!
