### ISSUE TITLE
Could anyone provide pre-trained model?

### ISSUE THREAD

**Issue by bung87** [dongjun-Lee/text-summarization-tensorflow#3]
It takes whole day still unfinished on my MBP,I don't have ideas of how long it will takes.

**Comment by dongjun-Lee** [comment]
Hi, I added a link for a pre-trained model (with default parameters and 10 epochs) at [README.md](https://github.com/dongjun-Lee/text-summarization-tensorflow/blob/master/README.md).

**Comment by bung87** [comment]
Thanks ! I'll try it later.
