### ISSUE TITLE
error test file

### ISSUE THREAD

**Issue by JenuTandel** [dongjun-Lee/text-summarization-tensorflow#33]
When I tried to run the test file , it gives keyerror. Please help me.
![error](https://user-images.githubusercontent.com/44287293/50506488-3a8e6880-0a9f-11e9-96d4-51a760f5b5b3.PNG)

**Comment by yash-1997** [comment]
> When I tried to run the test file , it gives keyerror. Please help me.
> ![error](https://user-images.githubusercontent.com/44287293/50506488-3a8e6880-0a9f-11e9-96d4-51a760f5b5b3.PNG)

How did you solve this error?
