### ISSUE TITLE
Error while trying to run test.py on pre-trained model

### ISSUE THREAD

**Issue by SundareshPrasanna** [dongjun-Lee/text-summarization-tensorflow#5]
Hi, 
I'm getting a KeyError -1 error at line 36 of test.py when trying to run for the pretrained model.

  File "test.py", line 36, in <listcomp>
    prediction_output = list(map(lambda x: [reversed_dict[y] for y in x], prediction[:, 0, :]))
KeyError: -1

May i know why it is throwing this error?

**Comment by dongjun-Lee** [comment]
Hi, could you specify how did you run the scripts? I can't reproduce this error. Thanks.

**Comment by SundareshPrasanna** [comment]
I downloaded the pretrained model, extracted them in the working directory & then ran the test.py file.

**Comment by dongjun-Lee** [comment]
How about the data? Which dataset did you use?

**Comment by SundareshPrasanna** [comment]
I pointed the valid_article_path & valid_title_path in utils.py file to point to "sumdata/train/valid.article.filter" & "valid.title.filter" files resp.

**Comment by dongjun-Lee** [comment]
I tested with Tensorflow 1.4.0 and I got the same error with you. It works on Tensorflow 1.8.0. Please update Tensorflow to use the code. I'll figure out why this error occurs on 1.4.0. Thank you!

**Comment by SundareshPrasanna** [comment]
Thanks Lee. I upgraded my TF version to 1.10.0 and it works fine in it. Thanks for your support :)

**Comment by dongjun-Lee** [comment]
You're welcome! :)
